sudo python3 ./run_ubenchmark.py \
	--app /home/ubuntu/dpdk/x86_64-native-linuxapp-gcc/examples/dpdk-tx_shaper_baseline \
 	--eal-args=--force-max-simd-bitwidth=64 \
       	--mechanism bql \
	--lcore-sets '1,2' \
	--repeats 30  \
	--rates 3125000000 \
       	--transient-types 0 \
     	--bql-interval-us 10 \
	--bql-grow-step 64 \
       	--descs 4096 \
       	--bursts 512  \
	--samples 500000 \
	--output 6.2_cbc_characterization
